image: node:8.9.4

before_script:
  - npm install

cache:
  paths:
  - node_modules/

stages:
  - test

test_proj:
  stage: test
  tags:
    - linux

  before_script:
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - ng test --single-run --progress false
    - ng e2e --progress false
  script:
    - ./node_modules/.bin/ng test --watch=false --code-coverage=true --browsers=ChromeHeadless
  artifacts:
    paths:
      - coverage/*
  coverage: '/(\d*.?\d+)%/'
